openapi: 3.0.1
info:
  description: SSM REST service specification
  title: SSM API Documentation
  version: 1.0.0
servers:
- description: Local SSM server url
  url: http://localhost:8081
tags:
- name: Rules
- name: Cmdlets
- name: Actions
- name: Files
- name: Cluster
paths:
  /api/v2/rules:
    get:
      operationId: getRules
      parameters:
      - explode: true
        in: query
        name: pageRequest
        required: false
        schema:
          $ref: '#/components/schemas/PageRequest'
      - description: The object's text representation filter
        in: query
        name: textRepresentationLike
        required: false
        schema:
          type: string
      - description: Time interval in which the entity was submitted
        explode: true
        in: query
        name: submissionTime
        required: false
        schema:
          $ref: '#/components/schemas/TimeInterval'
        style: deepObject
      - description: List of rule states
        in: query
        name: ruleStates
        required: false
        schema:
          items:
            $ref: '#/components/schemas/RuleState'
          type: array
      - description: Time interval in which the rule was activated
        explode: true
        in: query
        name: lastCheckTime
        required: false
        schema:
          $ref: '#/components/schemas/TimeInterval'
        style: deepObject
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rules'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Data is filled incorrectly
      summary: List all rules
      tags:
      - Rules
    post:
      operationId: addRule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitRuleRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rule'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Data is filled incorrectly
      summary: Submit rule
      tags:
      - Rules
  /api/v2/rules/{id}:
    delete:
      operationId: deleteRule
      parameters:
      - description: Id of the resource
        in: path
        name: id
        required: true
        schema:
          description: Reference to 'id' field
          format: int64
          type: integer
      responses:
        "200":
          description: Rule has been removed
        "404":
          description: Rule with specified id not found
      summary: Delete rule by id
      tags:
      - Rules
    get:
      operationId: getRule
      parameters:
      - description: Id of the resource
        in: path
        name: id
        required: true
        schema:
          description: Reference to 'id' field
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rule'
          description: OK
        "404":
          description: Rule with specified id not found
      summary: Get rule by id
      tags:
      - Rules
  /api/v2/rules/{id}/start:
    post:
      operationId: startRule
      parameters:
      - description: Id of the resource
        in: path
        name: id
        required: true
        schema:
          description: Reference to 'id' field
          format: int64
          type: integer
      responses:
        "200":
          description: Rule has been started
        "404":
          description: Rule with specified id not found
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unsupported state transition
      summary: Start or continue specified rule
      tags:
      - Rules
  /api/v2/rules/{id}/stop:
    post:
      operationId: stopRule
      parameters:
      - description: Id of the resource
        in: path
        name: id
        required: true
        schema:
          description: Reference to 'id' field
          format: int64
          type: integer
      responses:
        "200":
          description: Rule has been stopped
        "404":
          description: Rule with specified id not found
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unsupported state transition
      summary: Stop specified rule
      tags:
      - Rules
  /api/v2/cmdlets:
    get:
      operationId: getCmdlets
      parameters:
      - explode: true
        in: query
        name: pageRequest
        required: false
        schema:
          $ref: '#/components/schemas/PageRequest'
      - description: The object's text representation filter
        in: query
        name: textRepresentationLike
        required: false
        schema:
          type: string
      - description: Time interval in which the entity was submitted
        explode: true
        in: query
        name: submissionTime
        required: false
        schema:
          $ref: '#/components/schemas/TimeInterval'
        style: deepObject
      - description: Ids of the rules that cmdlets belong to
        in: query
        name: ruleIds
        required: false
        schema:
          items:
            format: int64
            type: integer
          type: array
      - description: List of cmdlet states
        in: query
        name: states
        required: false
        schema:
          items:
            $ref: '#/components/schemas/CmdletState'
          type: array
      - description: Time interval in which the state of the cmdlet was changed
        explode: true
        in: query
        name: stateChangedTime
        required: false
        schema:
          $ref: '#/components/schemas/TimeInterval'
        style: deepObject
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cmdlets'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Data is filled incorrectly
      summary: List all cmdlets
      tags:
      - Cmdlets
    post:
      operationId: addCmdlet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitCmdletRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cmdlet'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Data is filled incorrectly
      summary: Submit cmdlet
      tags:
      - Cmdlets
  /api/v2/cmdlets/{id}:
    delete:
      operationId: deleteCmdlet
      parameters:
      - description: Id of the resource
        in: path
        name: id
        required: true
        schema:
          description: Reference to 'id' field
          format: int64
          type: integer
      responses:
        "200":
          description: Cmdlet has been removed
        "404":
          description: Cmdlet with specified id not found
      summary: Delete cmdlet by id
      tags:
      - Cmdlets
    get:
      operationId: submitCmdlet
      parameters:
      - description: Id of the resource
        in: path
        name: id
        required: true
        schema:
          description: Reference to 'id' field
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cmdlet'
          description: OK
        "404":
          description: Cmdlet with specified id not found
      summary: Get cmdlet by id
      tags:
      - Cmdlets
  /api/v2/cmdlets/{id}/stop:
    post:
      operationId: stopCmdlet
      parameters:
      - description: Id of the resource
        in: path
        name: id
        required: true
        schema:
          description: Reference to 'id' field
          format: int64
          type: integer
      responses:
        "200":
          description: Cmdlet has been stopped
        "404":
          description: Cmdlet with specified id not found
      summary: Stop specified cmdlet
      tags:
      - Cmdlets
  /api/v2/actions:
    get:
      operationId: getActions
      parameters:
      - explode: true
        in: query
        name: pageRequest
        required: false
        schema:
          $ref: '#/components/schemas/PageRequest'
      - description: The object's text representation filter
        in: query
        name: textRepresentationLike
        required: false
        schema:
          type: string
      - description: Time interval in which the entity was submitted
        explode: true
        in: query
        name: submissionTime
        required: false
        schema:
          $ref: '#/components/schemas/TimeInterval'
        style: deepObject
      - description: List of hosts on which the action is/was running
        in: query
        name: hosts
        required: false
        schema:
          items:
            type: string
          type: array
      - description: List of cmdlet states
        in: query
        name: states
        required: false
        schema:
          items:
            $ref: '#/components/schemas/CmdletState'
          type: array
      - description: List of action sources
        in: query
        name: sources
        required: false
        schema:
          items:
            $ref: '#/components/schemas/ActionSource'
          type: array
      - description: Time interval in which the action was finished
        explode: true
        in: query
        name: completionTime
        required: false
        schema:
          $ref: '#/components/schemas/TimeInterval'
        style: deepObject
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Actions'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Data is filled incorrectly
      summary: List all actions
      tags:
      - Actions
    post:
      operationId: submitAction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitActionRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionInfo'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Data is filled incorrectly
      summary: Submit action
      tags:
      - Actions
  /api/v2/actions/{id}:
    get:
      operationId: getAction
      parameters:
      - description: Id of the resource
        in: path
        name: id
        required: true
        schema:
          description: Reference to 'id' field
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Action'
          description: OK
        "404":
          description: Action with specified id not found
      summary: Get action by id
      tags:
      - Actions
  /api/v2/files/access-counts:
    get:
      operationId: getAccessCounts
      parameters:
      - explode: true
        in: query
        name: pageRequest
        required: false
        schema:
          $ref: '#/components/schemas/PageRequest'
      - description: The file path filter
        in: query
        name: pathLike
        required: false
        schema:
          type: string
      - description: Time interval in which the file was accessed
        explode: true
        in: query
        name: lastAccessedTime
        required: false
        schema:
          $ref: '#/components/schemas/TimeInterval'
        style: deepObject
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileAccessCounts'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Data is filled incorrectly
      summary: List access counts of files
      tags:
      - Files
  /api/v2/files/cached:
    get:
      operationId: getCachedFiles
      parameters:
      - explode: true
        in: query
        name: pageRequest
        required: false
        schema:
          $ref: '#/components/schemas/PageRequest'
      - description: The file path filter
        in: query
        name: pathLike
        required: false
        schema:
          type: string
      - description: Time interval in which the file was accessed
        explode: true
        in: query
        name: lastAccessedTime
        required: false
        schema:
          $ref: '#/components/schemas/TimeInterval'
        style: deepObject
      - description: Time interval in which the file was cached
        explode: true
        in: query
        name: cachedTime
        required: false
        schema:
          $ref: '#/components/schemas/TimeInterval'
        style: deepObject
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CachedFiles'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Data is filled incorrectly
      summary: List cached files
      tags:
      - Files
  /api/v2/cluster/nodes:
    get:
      operationId: getClusterNodes
      parameters:
      - explode: true
        in: query
        name: pageRequest
        required: false
        schema:
          $ref: '#/components/schemas/PageRequest'
      - description: Time interval in which node was registered in master
        explode: true
        in: query
        name: registrationTime
        required: false
        schema:
          $ref: '#/components/schemas/TimeInterval'
        style: deepObject
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClusterNodes'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Data is filled incorrectly
      summary: List all cluster nodes
      tags:
      - Cluster
components:
  parameters:
    page-request:
      explode: true
      in: query
      name: pageRequest
      required: false
      schema:
        $ref: '#/components/schemas/PageRequest'
    text-representation-like:
      description: The object's text representation filter
      in: query
      name: textRepresentationLike
      required: false
      schema:
        type: string
    submission-time:
      description: Time interval in which the entity was submitted
      explode: true
      in: query
      name: submissionTime
      required: false
      schema:
        $ref: '#/components/schemas/TimeInterval'
      style: deepObject
    rule-states:
      description: List of rule states
      in: query
      name: ruleStates
      required: false
      schema:
        items:
          $ref: '#/components/schemas/RuleState'
        type: array
    last-activation-time:
      description: Time interval in which the rule was activated
      explode: true
      in: query
      name: lastCheckTime
      required: false
      schema:
        $ref: '#/components/schemas/TimeInterval'
      style: deepObject
    id:
      description: Id of the resource
      in: path
      name: id
      required: true
      schema:
        description: Reference to 'id' field
        format: int64
        type: integer
    rule-ids:
      description: Ids of the rules that cmdlets belong to
      in: query
      name: ruleIds
      required: false
      schema:
        items:
          format: int64
          type: integer
        type: array
    states:
      description: List of cmdlet states
      in: query
      name: states
      required: false
      schema:
        items:
          $ref: '#/components/schemas/CmdletState'
        type: array
    state-changed-time:
      description: Time interval in which the state of the cmdlet was changed
      explode: true
      in: query
      name: stateChangedTime
      required: false
      schema:
        $ref: '#/components/schemas/TimeInterval'
      style: deepObject
    hosts:
      description: List of hosts on which the action is/was running
      in: query
      name: hosts
      required: false
      schema:
        items:
          type: string
        type: array
    sources:
      description: List of action sources
      in: query
      name: sources
      required: false
      schema:
        items:
          $ref: '#/components/schemas/ActionSource'
        type: array
    completion-time:
      description: Time interval in which the action was finished
      explode: true
      in: query
      name: completionTime
      required: false
      schema:
        $ref: '#/components/schemas/TimeInterval'
      style: deepObject
    path-like:
      description: The file path filter
      in: query
      name: pathLike
      required: false
      schema:
        type: string
    last-accessed-time:
      description: Time interval in which the file was accessed
      explode: true
      in: query
      name: lastAccessedTime
      required: false
      schema:
        $ref: '#/components/schemas/TimeInterval'
      style: deepObject
    cached-time:
      description: Time interval in which the file was cached
      explode: true
      in: query
      name: cachedTime
      required: false
      schema:
        $ref: '#/components/schemas/TimeInterval'
      style: deepObject
    registration-time:
      description: Time interval in which node was registered in master
      explode: true
      in: query
      name: registrationTime
      required: false
      schema:
        $ref: '#/components/schemas/TimeInterval'
      style: deepObject
  schemas:
    PageRequest:
      properties:
        limit:
          default: 10
          description: Maximum number of records in result set
          minimum: 1
          nullable: true
          type: integer
        offset:
          default: 0
          description: Offset of the first record to search from
          nullable: true
          type: integer
        sort:
          description: Sort field names prefixed with '-' for descending order
          items:
            type: string
          nullable: true
          type: array
      title: PageRequest
      type: object
    TimeInterval:
      properties:
        from:
          description: UNIX timestamp (UTC) of the interval start
          format: int64
          nullable: true
          type: integer
        to:
          description: UNIX timestamp (UTC) of the interval end
          format: int64
          nullable: true
          type: integer
      title: TimeInterval
      type: object
    RuleState:
      description: Current state of the rule
      enum:
      - ACTIVE
      - DISABLED
      title: RuleState
      type: string
    PageResponse:
      properties:
        total:
          description: Total number of objects
          type: integer
        items:
          items:
            type: object
          type: array
      required:
      - total
      title: PageResponse
      type: object
    Rule:
      example:
        submitTime: 1
        activationCount: 5
        textRepresentation: textRepresentation
        lastActivationTime: 2
        id: 6
        state: null
        cmdletsGenerated: 5
      properties:
        id:
          description: Rule id
          format: int64
          type: integer
        submitTime:
          description: UNIX timestamp (UTC) of the rule submission
          format: int64
          type: integer
        textRepresentation:
          description: Rule text representation
          type: string
        state:
          $ref: '#/components/schemas/RuleState'
        activationCount:
          description: Number of rule activations
          format: int64
          type: integer
        cmdletsGenerated:
          description: Number of generated cmdlets from this rule
          format: int64
          type: integer
        lastActivationTime:
          description: UNIX timestamp (UTC) of the last rule activation
          format: int64
          nullable: true
          type: integer
      required:
      - activationCount
      - cmdletsGenerated
      - id
      - state
      - submitTime
      - textRepresentation
      title: Rule
      type: object
    ErrorResponse:
      example:
        code: code
        message: message
        body: "{}"
      properties:
        code:
          description: Error code
          type: string
        message:
          description: Detailed error message
          type: string
        body:
          description: Additional information about the error
          type: object
      required:
      - code
      - message
      title: ErrorResponse
      type: object
    SubmitRuleRequest:
      example:
        rule: rule
      properties:
        rule:
          description: Rule text representation
          type: string
      required:
      - rule
      title: SubmitRuleRequest
      type: object
    CmdletState:
      description: Current state of the cmdlet
      enum:
      - NOT_INITED
      - PENDING
      - SCHEDULED
      - DISPATCHED
      - EXECUTING
      - CANCELLED
      - DISABLED
      - FAILED
      - DONE
      title: CmdletState
      type: string
    Cmdlet:
      example:
        actionIds:
        - 5
        - 5
        stateChangedTime: 2
        textRepresentation: textRepresentation
        id: 6
        state: null
        ruleId: 1
        submissionTime: 5
      properties:
        id:
          description: Cmdlet id
          format: int64
          type: integer
        ruleId:
          description: Id of the rule that generated cmdlet
          format: int64
          nullable: true
          type: integer
        actionIds:
          description: List of the action ids belonging to the current cmdlet
          items:
            format: int64
            type: integer
          type: array
        state:
          $ref: '#/components/schemas/CmdletState'
        textRepresentation:
          description: Cmdlet text representation
          type: string
        submissionTime:
          description: UNIX timestamp (UTC) of the cmdlet submission
          format: int64
          type: integer
        stateChangedTime:
          description: UNIX timestamp (UTC) of the cmdlet state modification
          format: int64
          type: integer
      required:
      - actionIds
      - id
      - state
      - stateChangedTime
      - submissionTime
      - textRepresentation
      title: Cmdlet
      type: object
    SubmitCmdletRequest:
      example:
        cmdlet: cmdlet
      properties:
        cmdlet:
          description: Cmdlet text representation
          type: string
      required:
      - cmdlet
      title: SubmitCmdletRequest
      type: object
    ActionSource:
      description: Source of the action creation
      enum:
      - RULE
      - USER
      title: ActionSource
      type: string
    ActionInfo:
      example:
        completionTime: 5
        textRepresentation: textRepresentation
        execHost: execHost
        id: 6
        state: null
        source: null
        cmdletId: 1
        submissionTime: 5
      properties:
        id:
          description: Action id
          format: int64
          type: integer
        cmdletId:
          description: Id of the cmdlet this action belongs to
          format: int64
          type: integer
        textRepresentation:
          description: Action text representation
          type: string
        execHost:
          description: SSM host on which this action is running
          nullable: true
          type: string
        submissionTime:
          description: UNIX timestamp (UTC) of the action submission
          format: int64
          type: integer
        completionTime:
          description: UNIX timestamp (UTC) of the action completion
          format: int64
          nullable: true
          type: integer
        state:
          $ref: '#/components/schemas/ActionState'
        source:
          $ref: '#/components/schemas/ActionSource'
      required:
      - cmdletId
      - id
      - source
      - state
      - submissionTime
      - textRepresentation
      title: ActionInfo
      type: object
    SubmitActionRequest:
      example:
        action: action
      properties:
        action:
          description: Action text representation
          type: string
      required:
      - action
      title: SubmitActionRequest
      type: object
    Action:
      allOf:
      - $ref: '#/components/schemas/ActionInfo'
      - properties:
          log:
            description: Action log
            type: string
        type: object
      example:
        completionTime: 5
        log: log
        textRepresentation: textRepresentation
        execHost: execHost
        id: 0
        state: null
        source: null
        cmdletId: 6
        submissionTime: 1
      required:
      - cmdletId
      - id
      - source
      - state
      - submissionTime
      - textRepresentation
      title: Action
      type: object
    FileAccessInfo:
      example:
        path: path
        accessCount: 1
        lastAccessTime: 5
        id: 6
      properties:
        id:
          description: Id of the file
          format: int64
          type: integer
        path:
          description: Path of the file
          type: string
        accessCount:
          description: Number of accesses to the file
          format: int32
          type: integer
        lastAccessTime:
          description: UNIX timestamp (UTC) of the last file access
          format: int32
          type: integer
      required:
      - accessCount
      - id
      - lastAccessTime
      - path
      title: FileAccessInfo
      type: object
    CachedFileInfo:
      example:
        path: path
        accessCount: 1
        lastAccessTime: 5
        id: 6
        cachedTime: 5
      properties:
        id:
          description: Id of the file
          format: int64
          type: integer
        path:
          description: Path of the file
          type: string
        accessCount:
          description: Number of accesses to the file
          format: int32
          type: integer
        cachedTime:
          description: UNIX timestamp (UTC) when the file was cached
          format: int32
          type: integer
        lastAccessTime:
          description: UNIX timestamp (UTC) of the last file access
          format: int32
          type: integer
      required:
      - accessCount
      - cachedTime
      - id
      - lastAccessTime
      - path
      title: CachedFileInfo
      type: object
    ClusterNode:
      example:
        registrationTime: 1
        executorType: null
        port: 6
        host: host
        cmdletsExecuted: 5
        id: id
        executorsCount: 5
      properties:
        id:
          description: id of the node
          type: string
        host:
          description: host on which the node is running
          type: string
        port:
          description: port to which the node is bound
          format: int32
          type: integer
        executorType:
          $ref: '#/components/schemas/ExecutorType'
        registrationTime:
          description: UNIX timestamp (UTC) of the node registration in master
          format: int64
          type: integer
        executorsCount:
          description: Number of cmdlet executors
          format: int32
          type: integer
        cmdletsExecuted:
          description: Number of executed cmdlets on this node
          format: int64
          type: integer
      required:
      - cmdletsExecuted
      - executorType
      - executorsCount
      - host
      - id
      - port
      - registrationTime
      title: ClusterNode
      type: object
    ActionState:
      description: State of the action
      enum:
      - RUNNING
      - SUCCESSFUL
      - FAILED
      title: ActionState
      type: string
    ExecutorType:
      description: Type of the cmdlet executor
      enum:
      - LOCAL
      - REMOTE_SSM
      - AGENT
      title: ExecutorType
      type: string
    Rules:
      allOf:
      - $ref: '#/components/schemas/PageResponse'
      - properties:
          items:
            description: List of rules
            items:
              $ref: '#/components/schemas/Rule'
            type: array
        type: object
      example:
        total: 0
        items:
        - submitTime: 1
          activationCount: 5
          textRepresentation: textRepresentation
          lastActivationTime: 2
          id: 6
          state: null
          cmdletsGenerated: 5
        - submitTime: 1
          activationCount: 5
          textRepresentation: textRepresentation
          lastActivationTime: 2
          id: 6
          state: null
          cmdletsGenerated: 5
      title: Rules
    Cmdlets:
      allOf:
      - $ref: '#/components/schemas/PageResponse'
      - properties:
          items:
            description: List of cmdlets
            items:
              $ref: '#/components/schemas/Cmdlet'
            type: array
        type: object
      example:
        total: 0
        items:
        - actionIds:
          - 5
          - 5
          stateChangedTime: 2
          textRepresentation: textRepresentation
          id: 6
          state: null
          ruleId: 1
          submissionTime: 5
        - actionIds:
          - 5
          - 5
          stateChangedTime: 2
          textRepresentation: textRepresentation
          id: 6
          state: null
          ruleId: 1
          submissionTime: 5
      title: Cmdlets
    Actions:
      allOf:
      - $ref: '#/components/schemas/PageResponse'
      - properties:
          items:
            description: List of actions
            items:
              $ref: '#/components/schemas/ActionInfo'
            type: array
        type: object
      example:
        total: 0
        items:
        - completionTime: 5
          textRepresentation: textRepresentation
          execHost: execHost
          id: 6
          state: null
          source: null
          cmdletId: 1
          submissionTime: 5
        - completionTime: 5
          textRepresentation: textRepresentation
          execHost: execHost
          id: 6
          state: null
          source: null
          cmdletId: 1
          submissionTime: 5
      title: Actions
    FileAccessCounts:
      allOf:
      - $ref: '#/components/schemas/PageResponse'
      - properties:
          items:
            description: List of files
            items:
              $ref: '#/components/schemas/FileAccessInfo'
            type: array
        type: object
      example:
        total: 0
        items:
        - path: path
          accessCount: 1
          lastAccessTime: 5
          id: 6
        - path: path
          accessCount: 1
          lastAccessTime: 5
          id: 6
      title: FileAccessCounts
    CachedFiles:
      allOf:
      - $ref: '#/components/schemas/PageResponse'
      - properties:
          items:
            description: List of files
            items:
              $ref: '#/components/schemas/CachedFileInfo'
            type: array
        type: object
      example:
        total: 0
        items:
        - path: path
          accessCount: 1
          lastAccessTime: 5
          id: 6
          cachedTime: 5
        - path: path
          accessCount: 1
          lastAccessTime: 5
          id: 6
          cachedTime: 5
      title: CachedFiles
    ClusterNodes:
      allOf:
      - $ref: '#/components/schemas/PageResponse'
      - properties:
          items:
            description: List of SSM cluster nodes
            items:
              $ref: '#/components/schemas/ClusterNode'
            type: array
        type: object
      example:
        total: 0
        items:
        - registrationTime: 1
          executorType: null
          port: 6
          host: host
          cmdletsExecuted: 5
          id: id
          executorsCount: 5
        - registrationTime: 1
          executorType: null
          port: 6
          host: host
          cmdletsExecuted: 5
          id: id
          executorsCount: 5
      title: ClusterNodes
